apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: kennethreitz/httpbin:latest
          ports:
            - containerPort: 80
          env:
            - name: FEATURE_FLAG_X
              value: "true"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
